import { LocationItem, RouteResult } from "../types";
import { APP_NAME } from "../constants";

export const generateOfflineHTML = (
  locations: LocationItem[],
  route: RouteResult
): string => {
  const orderedLocations = route.sequence
    .map(id => locations.find(l => l.id === id))
    .filter(Boolean) as LocationItem[];

  const dateStr = new Date().toISOString().split('T')[0];
  
  return `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${APP_NAME} - ${dateStr}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: #fff; color: #000; padding: 20px; max-width: 600px; margin: 0 auto; }
        h1 { border-bottom: 2px solid #000; padding-bottom: 10px; }
        .advice { background: #f3f4f6; padding: 15px; border-left: 4px solid #000; margin-bottom: 20px; font-style: italic; }
        .timeline { position: relative; padding-left: 20px; border-left: 2px dashed #000; margin-left: 10px; }
        .stop { margin-bottom: 30px; position: relative; }
        .stop-dot { position: absolute; left: -26px; top: 0; width: 14px; height: 14px; background: #000; border-radius: 50%; color: white; font-size: 10px; display: flex; align-items: center; justify-content: center; font-weight: bold; border: 2px solid #fff; box-shadow: 0 0 0 1px #000; }
        .card { border: 1px solid #000; padding: 15px; box-shadow: 4px 4px 0 0 #000; background: white; }
        .card h3 { margin: 0 0 5px 0; }
        .meta { font-size: 12px; color: #666; margin-bottom: 10px; }
        .actions { margin-top: 10px; display: flex; gap: 10px; }
        a.btn { text-decoration: none; border: 1px solid #000; padding: 5px 10px; font-size: 12px; color: #000; font-weight: bold; display: inline-block; transition: all 0.1s; }
        a.btn:active { transform: translate(2px, 2px); }
        .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #999; }
    </style>
</head>
<body>
    <h1>行程单: ${dateStr}</h1>
    
    <div class="advice">
        <strong>智能导游:</strong> ${route.advice}
    </div>

    <div class="timeline">
        ${orderedLocations.map((loc, index) => `
        <div class="stop">
            <div class="stop-dot">${index + 1}</div>
            <div class="card">
                <h3>${loc.name}</h3>
                <div class="meta">${loc.city} · ${loc.type}</div>
                <p>"${loc.context}"</p>
                <div class="actions">
                    <a href="iosamap://path?source=TripSpot&dlat=${loc.lat}&dlon=${loc.lng}&dname=${encodeURIComponent(loc.name)}" class="btn">🚀 导航</a>
                    <a href="bilibili://search?keyword=${encodeURIComponent(loc.name + "攻略")}" class="btn">📺 攻略</a>
                </div>
            </div>
        </div>
        `).join('')}
    </div>

    <div class="footer">
        Generated by 旅点 TripSpot v1.5
    </div>
</body>
</html>
  `;
};